### ISSUE TITLE
Renaming templates

### ISSUE THREAD

**Issue by tympanix** [tympanix/supper#15]
Provide a templating configuration option to allow users to specify a custom renaming format. Should utilize the [go templating language](https://golang.org/pkg/text/template/). This could be e.g.
```yaml
rename:
  movies: "{{ .Name }} ({{ .Year }})"
  shows: "{{ .TVShow }} - E{{ .Episode }}S{{ .Season }} - {{ .Title }}"
```

Should also provide:
 - [ ] Padding with zeros for season/episode number
 - [ ] Escaping of special characters not allows in filenames
 - [ ] A [func map](https://golang.org/pkg/text/template/#Template.Funcs) with some utility formatting functions
